AWSTemplateFormatVersion: '2010-09-09'
Description: > 
            CloudFormation template for EC2 instance with custom security group
            and custom ssh key (EC2 Key pair)

Parameters:
  SshKeyName:
    Type: String
    Default: "neptun-id_ed25519"
    Description: "Provide name of key pair that exist in your region!"

Resources:
  MyEC2InstanceUbuntu:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t3.micro
      ImageId: ami-0989fb15ce71ba39e # This is a placeholder AMI ID, replace with your desired AMI ID.
      KeyName: !Ref SshKeyName     # Ensure this key pair exists in your region
      SecurityGroups:
        - !Ref MySecurityGroup
      Tags:
          - Value: "myUbuntu"
            Key: Name
          - Value: ubuntu
            Key: login_name
           

  MyEC2InstanceAmazon:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t3.micro
      # FIXIT: provide ami for amz
      ImageId: ami-065681da47fb4e433 # This is a placeholder AMI ID, replace with your desired AMI ID.
      KeyName: !Ref SshKeyName     # Ensure this key pair exists in your region
      SecurityGroups:
        - !Ref MySecurityGroup
      Tags:
          - Value: "myAmazon"
            Key: Name
          - Value: ec2-user
            Key: login_name

  MySecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Custom Security Group for MyEC2Instance
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0        # Open to the world for demonstration purposes. Modify or restrict as needed.

Outputs:
  UbuntuInstanceId:
    Description: Ubuntu EC2 Instance ID
    Value: !Ref MyEC2InstanceUbuntu

  AmzInstanceId:
    Description: Amazon EC2 Instance ID
    Value: !Ref MyEC2InstanceAmazon

  SecurityGroupId:
    Description: Security Group ID
    Value: !Ref MySecurityGroup
